---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Find proxy certs file
      ansible.builtin.stat:
        path: /root/proxy.example.com.tar.gz
      register: __foreman_cert_tarball

    - name: Check proxy certs file exists
      ansible.builtin.assert:
        that:
          - __foreman_cert_tarball.stat.exists
