---
- name: Create systemd drop-in directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/rhcd.service.d
    owner: root
    group: root
    mode: '0755'

- name: Deploy HTTP proxy systemd drop-in file
  ansible.builtin.template:
    src: "proxy.conf.j2"
    dest: /etc/systemd/system/rhcd.service.d/proxy.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart rhcd
