---
- name: 'Install centos-release-ansible29 on EL8'  # noqa package-latest
  dnf:
    name: centos-release-ansible-29
    state: latest
    update_cache: true
  tags:
    - packages
  when:
    - ansible_distribution_major_version == '8'
