---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    foreman_installer_scenario: foreman
  roles:
    - role: installer
      vars:
        foreman_installer_options:
          - '--foreman-initial-organization "Test Org"'
    - role: installer
      vars:
        foreman_installer_options:
          - '--enable-foreman-plugin-tasks'
