---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Foreman is installed
      package:
        name: foreman
        state: present

    - name: Find installer flag file
      stat:
        path: /etc/foreman-installer/scenarios.d/.installed
      register: installed_file
    - name: Assert installer flag file exists
      assert:
        that:
          - installed_file.stat.exists

    - name: Find tasks config file
      stat:
        path: /etc/foreman/plugins/foreman-tasks.yaml
      register: foreman_tasks_yaml
    - name: Check tasks config file exists
      assert:
        that:
          - foreman_tasks_yaml.stat.exists
