---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Foreman is installed
      ansible.builtin.package:
        name: foreman
        state: present

    - name: Find installer flag file
      ansible.builtin.stat:
        path: /etc/foreman-installer/scenarios.d/.installed
      register: __foreman_installed_file
    - name: Assert installer flag file exists
      ansible.builtin.assert:
        that:
          - __foreman_installed_file.stat.exists

    - name: Find tasks config file
      ansible.builtin.stat:
        path: /etc/foreman/plugins/foreman-tasks.yaml
      register: __foreman_tasks_yaml
    - name: Check tasks config file exists
      ansible.builtin.assert:
        that:
          - __foreman_tasks_yaml.stat.exists
