---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure centos-release-ansible-29 RPM is installed
      package:
        name: centos-release-ansible-29
        state: present
