---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: debian-bullseye
    image: debian:11
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint .
  YAMLLINT_CONFIG_FILE=../../.yamllint ansible-lint .
