---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Configure Foreman rpeositories
      ansible.builtin.include_role:
        name: foreman_repositories
      vars:
        foreman_repositories_version: 'nightly'

    - name: Install PostgreSQL
      ansible.builtin.package:
        name: postgresql
        state: present

    - name: Start PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: started
