---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure foreman-release is installed
      ansible.builtin.package:
        name: foreman-release
        state: present

    - name: Ensure katello-repos is installed
      ansible.builtin.package:
        name: katello-repos
        state: present

    - name: Stat foreman.repo
      ansible.builtin.stat:
        path: /etc/yum.repos.d/foreman.repo
      register: foreman_repo

    - name: Check foreman_repo file exists
      ansible.builtin.assert:
        that:
          - foreman_repo.stat.exists

    - name: Stat foreman-plugins.repo
      ansible.builtin.stat:
        path: /etc/yum.repos.d/foreman-plugins.repo
      register: foreman_plugins_repo

    - name: Check foreman_plugins_repo file exists
      ansible.builtin.assert:
        that:
          - foreman_plugins_repo.stat.exists

    - name: Stat katello.repo
      ansible.builtin.stat:
        path: /etc/yum.repos.d/katello.repo
      register: foreman_katello_repo

    - name: Check katello_repo file exists
      ansible.builtin.assert:
        that:
          - foreman_katello_repo.stat.exists
