---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure puppet5-release package is absent
      package:
        name: puppet5-release
        state: absent

    - name: Ensure puppet6-release package is absent
      package:
        name: puppet6-release
        state: absent

    - name: Ensure puppet7-release package is present
      package:
        name: puppet7-release
        state: present
