---
- name: Prepare
  hosts: foreman
  gather_facts: true
  become: true
  vars:
    foreman_repositories_version: 'nightly'  # Testing Ruby 2.7 enable, switch to 2.5 when released
  roles:
    - role: foreman_repositories
    - role: freeipa.ansible_freeipa.ipaclient
      vars:
        ipaadmin_password: changeme
