---
- name: 'Install Foreman GPG key'
  ansible.builtin.get_url:
    url: https://deb.theforeman.org/foreman.asc
    dest: /etc/apt/trusted.gpg.d/foreman.asc
    mode: '0444'

- name: 'Setup repository for Foreman {{ foreman_repositories_version }}'
  ansible.builtin.apt_repository:
    repo: deb http://deb.theforeman.org {{ ansible_distribution_release }} {{ foreman_repositories_version }}
    state: present

- name: 'Setup repository for Foreman Plugins {{ foreman_repositories_version }}'
  ansible.builtin.apt_repository:
    repo: deb http://deb.theforeman.org plugins {{ foreman_repositories_version }}
    state: present
