---
- name: 'Install centos-release-scl-rh on CentOS7'  # noqa package-latest
  ansible.builtin.yum:
    name: centos-release-scl-rh
    state: latest
    update_cache: true
  tags:
    - packages
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: 'Setup repository for Foreman {{ foreman_repositories_version }}'
  ansible.builtin.yum:
    name: https://yum.theforeman.org/releases/{{ foreman_repositories_version }}/el{{ ansible_distribution_major_version }}/x86_64/foreman-release.rpm
    disable_gpg_check: true
    state: present
  tags:
    - packages

- name: 'Setup repository for Katello {{ foreman_repositories_katello_version }}'
  ansible.builtin.yum:
    name: https://yum.theforeman.org/katello/{{ foreman_repositories_katello_version }}/katello/el{{ ansible_distribution_major_version }}/x86_64/katello-repos-latest.rpm
    disable_gpg_check: true
    state: present
  tags:
    - packages
  when:
    - foreman_repositories_katello_version is defined

- name: 'Enable modules on EL8'
  ansible.builtin.include_tasks: redhat-modules.yml
  when:
    - ansible_distribution_major_version == '8'

- name: Enable powertools for Katello
  when:
    - foreman_repositories_katello_version is defined
    - ansible_distribution_major_version == '8'
  block:
    - name: Install dnf-config-manager
      ansible.builtin.package:
        name: dnf-plugins-core
        state: present

    - name: Check if powertools repository is disabled
      ansible.builtin.command: dnf repolist --disabled powertools
      register: disabled_repos
      changed_when: false

    - name: Enable powertools
      ansible.builtin.command: dnf config-manager --set-enabled powertools
      register: dnf_set_enabled
      changed_when: dnf_set_enabled.rc is defined and dnf_set_enabled.rc == '0'
      when:
        - "'powertools' in disabled_repos.stdout"
        - ansible_distribution != 'RedHat'
