---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure langpacks on EL8
      ansible.builtin.dnf:
        name: glibc-langpack-en
        state: present

    - name: Install PostgreSQL 10
      ansible.builtin.dnf:
        name: '@postgresql:10/server'
        state: present

    - name: Run postgresql-setup --initdb
      ansible.builtin.command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION
