---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: centos8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp:exec,mode=777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint .
  YAMLLINT_CONFIG_FILE=../../.yamllint ansible-lint .
