---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Validation tests passed in converge
      ansible.builtin.debug:
        msg: All expected validation failures were caught correctly
